import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import Navbar from '../../components/Navbar';
import MuxPlayer from '@mux/mux-player-react';
import { useEffect, useState } from 'react';

const VideoPlayerPage: NextPage = () => {
  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
  const [video, setVideo] = useState({});
  const router = useRouter();
  const { playbackId } = router.query;

  const { status } = useSession();

  const fetchData = async () => {
    const response = await fetch(`${BASE_URL}api/video/${playbackId}`);
    const temp = await response.json();
    setVideo(temp);
    console.log(temp);
  };

  useEffect(() => {
    if (playbackId) {
      console.log(playbackId);
      fetchData();
    }

    return () => {};
  }, [playbackId]);

  if (status === 'loading') {
    return <></>;
  }
  if (status === 'unauthenticated') {
    router.push('/login');
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='videoPage'>
        <Navbar />
        <div className='videoPlayer'>
          {video ? (
            <>
              <MuxPlayer
                style={{ width: '80%' }}
                streamType='on-demand'
                playbackId={video.playbackId}
                title={video.name}
              />
              <h1>{video.name}</h1>
              <p>{video.description}</p>
            </>
          ) : (
            <></>
          )}
        </div>
      </main>
    </>
  );
};

export default VideoPlayerPage;
