import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import Navbar from '../../components/Navbar';
import MuxPlayer from '@mux/mux-player-react';

const VideoPlayerPage: NextPage = () => {
  const router = useRouter();
  const storedVideo = localStorage.getItem('video');

  if (!storedVideo) {
    router.push('/');
  }
  const video = JSON.parse(storedVideo || '{}');

  const { data: session, status } = useSession();

  if (status === 'loading') {
    return <></>;
  }
  if (status === 'unauthenticated') {
    router.push('/login');
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='videoPage'>
        <Navbar />
        <div className='videoPlayer'>
          <MuxPlayer
            style={{ width: '80%' }}
            streamType='on-demand'
            playbackId='cFhfcxddnJB6s3sTmOMy00vetWzj4NXaXgcZLB94pB024.m3u8'
            title={video.name}
          />
          <h1>{video.name}</h1>
          <p>{video.description}</p>
        </div>
      </main>
    </>
  );
};

export default VideoPlayerPage;
