import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Card from '../components/Card';

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [videos, setVideos] = useState([]);

  const fetchData = async () => {
    const response = await fetch(`api/video`);
    const temp = await response.json();
    setVideos(temp);
    console.log(temp);
  };
  useEffect(() => {
    fetchData();
  }, []);

  if (status === 'loading') {
    return <></>;
  }
  if (status === 'unauthenticated') {
    router.push('/login');
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        {session?.user ? (
          <>
            <ul className='container wrapper'>
              {videos?.map((video, index) => {
                return (
                  <li key={index} className=''>
                    <Card video={video} />
                  </li>
                );
              })}
            </ul>
          </>
        ) : (
          <></>
        )}
      </main>
    </>
  );
};

export default Home;
