import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession, signOut } from 'next-auth/react';
import Image from 'next/image';
import { useRouter } from 'next/router';
import VideoPlayer from '../components/VideoPlayer';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();

  if (status === 'loading') {
    return <></>;
  }
  if (status === 'unauthenticated') {
    router.push('/login');
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        {session ? (
          <div className='container'>
            <h1>{session.user?.name}</h1>
            <p>{session.user?.email}</p>
            <Image
              src={session.user?.image || ''}
              width={100}
              height={100}
              alt={'userImage'}
            />
            <VideoPlayer />
          </div>
        ) : (
          <></>
        )}
      </main>
    </>
  );
};

export default Home;
