import Head from 'next/head';
import { useRouter } from 'next/router';
function Login() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='back'>
        <div className='container full'>
          <div className='cover-container d-flex w-100 h-100 p-3 mx-auto flex-column full'>
            <div className='px-3 text-center blur'>
              <h1>Unlimited movies, TV shows, and more.</h1>
              <p className='lead'>
                Start a new story every day. Enjoy our Originals and premieres.
                Enjoy the best of Lolipop. Your favorite classics. Sign up now.
                Download it and enjoy. Enjoy streaming.
              </p>
              <button
                className='btn btn-info'
                onClick={() => router.push('/api/auth/signin')}
              >
                signin
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Login;

/* <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div> */
