import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import VideoPlayer from '../components/VideoPlayer';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();

  if (status === 'loading') {
    return <></>;
  }
  if (status === 'unauthenticated') {
    router.push('/login');
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Lolipop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='pricing'>
        <Navbar />
        <div className='container'>
          <div className='pricing-header p-3 pb-md4 mx-auto text-center'>
            <h1 className='display-4 fw-normal'>Pricing</h1>
            <p className='fs-5'>
              Quickly build an effective pricing table for your potential
              customers with this Bootstrap example. It’s built with default
              Bootstrap components and utilities with little customization.
            </p>
          </div>
          <div className='row row-cols-1 row-cols-md-3 mb-3 text-center'>
            <div className='col'>
              <div className='card mb-4 rounded-3 shadow-sm'>
                <div className='card-header py-3'>
                  <h4 className='my-0 fw-normal'>Mobile</h4>
                </div>
                <div className='card-body'>
                  <h1 className='card-title pricing-card-title'>
                    $1<small className='text-muted fw-light'>/mo</small>
                  </h1>
                  <ul className='list-unstyled mt-3 mb-4'>
                    <li>only 1 screen</li>
                    <li>Cellphone</li>
                    <li>Tablet</li>
                    <li>Help center access</li>
                  </ul>
                  <button
                    type='button'
                    className='w-100 btn btn-lg btn-outline-primary'
                  >
                    Join
                  </button>
                </div>
              </div>
            </div>
            <div className='col'>
              <div className='card mb-4 rounded-3 shadow-sm'>
                <div className='card-header py-3'>
                  <h4 className='my-0 fw-normal'>Full</h4>
                </div>
                <div className='card-body'>
                  <h1 className='card-title pricing-card-title'>
                    $3<small className='text-muted fw-light'>/mo</small>
                  </h1>
                  <ul className='list-unstyled mt-3 mb-4'>
                    <li>2 screens</li>
                    <li>Cellphone</li>
                    <li>Tablet</li>
                    <li>Tv</li>
                  </ul>
                  <button
                    type='button'
                    className='w-100 btn btn-lg btn-primary'
                  >
                    Join
                  </button>
                </div>
              </div>
            </div>
            <div className='col'>
              <div className='card mb-4 rounded-3 shadow-sm border-primary'>
                <div className='card-header py-3 text-white bg-primary border-primary'>
                  <h4 className='my-0 fw-normal'>Family</h4>
                </div>
                <div className='card-body'>
                  <h1 className='card-title pricing-card-title'>
                    $5<small className='text-muted fw-light'>/mo</small>
                  </h1>
                  <ul className='list-unstyled mt-3 mb-4'>
                    <li>5 screens</li>
                    <li>Cellphone</li>
                    <li>Tablet</li>
                    <li>Tv</li>
                  </ul>
                  <button
                    type='button'
                    className='w-100 btn btn-lg btn-primary'
                  >
                    Join
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
